version: '3' 

services: 
    simple-web-service:  
      image: devopsdockeruh/simple-web-service
      volumes: 
        - C:/Users/User1/devops-2021/part2/exercise2_1/text.log:/usr/src/app/text.log
      build: . 