version: '3'

services:
      
  db:
      image: postgres:13.2
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db_backend

  backend:
      image: example-backend
      ports:
        - 8080:8080
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_HOST=db
        - REDIS_HOST=redis
      depends_on:
        - db
        
  frontend:
      image: example-frontend
      ports:
        - 5000:5000

  adminer:
      image: adminer
      restart: always
      ports:
        - 8083:8080
      environment:
        - ADMINER_DESIGN=galkaev
        
  redis:
      image: redis
      
  nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - frontend
        - backend
      ports:
         - 80:80
         
